# The theme setting for a remote theme on GitHub Pages
remote_theme: pages-themes/cayman@v0.2.0

# This plugin is required for remote themes to work
plugins:
  - jekyll-remote-theme

title: Muhammad Saad Khalid
description: Welcome to my porfolio Website! Feel free to look around and contact me if necessary!
